// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Account defines model for Account.
type Account struct {
	AccessToken           *string    `json:"accessToken,omitempty"`
	AccessTokenExpiresAt  *time.Time `json:"accessTokenExpiresAt,omitempty"`
	AccountId             string     `json:"accountId"`
	CreatedAt             time.Time  `json:"createdAt"`
	Id                    *string    `json:"id,omitempty"`
	IdToken               *string    `json:"idToken,omitempty"`
	Password              *string    `json:"password,omitempty"`
	ProviderId            string     `json:"providerId"`
	RefreshToken          *string    `json:"refreshToken,omitempty"`
	RefreshTokenExpiresAt *time.Time `json:"refreshTokenExpiresAt,omitempty"`
	Scope                 *string    `json:"scope,omitempty"`
	UpdatedAt             time.Time  `json:"updatedAt"`
	UserId                string     `json:"userId"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	CreatedAt      time.Time `json:"createdAt"`
	Email          string    `json:"email"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Id             *string   `json:"id,omitempty"`
	InviterId      string    `json:"inviterId"`
	OrganizationId string    `json:"organizationId"`
	Role           *string   `json:"role,omitempty"`
	Status         string    `json:"status"`
	TeamId         *string   `json:"teamId,omitempty"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt      time.Time `json:"createdAt"`
	Id             *string   `json:"id,omitempty"`
	OrganizationId string    `json:"organizationId"`
	Role           string    `json:"role"`
	UserId         string    `json:"userId"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        *string   `json:"id,omitempty"`
	Logo      *string   `json:"logo,omitempty"`
	Metadata  *string   `json:"metadata,omitempty"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

// Session defines model for Session.
type Session struct {
	ActiveOrganizationId *string   `json:"activeOrganizationId,omitempty"`
	ActiveTeamId         *string   `json:"activeTeamId,omitempty"`
	CreatedAt            time.Time `json:"createdAt"`
	ExpiresAt            time.Time `json:"expiresAt"`
	Id                   *string   `json:"id,omitempty"`
	IpAddress            *string   `json:"ipAddress,omitempty"`
	Token                string    `json:"token"`
	UpdatedAt            time.Time `json:"updatedAt"`
	UserAgent            *string   `json:"userAgent,omitempty"`
	UserId               string    `json:"userId"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt      time.Time  `json:"createdAt"`
	Id             *string    `json:"id,omitempty"`
	Name           string     `json:"name"`
	OrganizationId string     `json:"organizationId"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	TeamId    string     `json:"teamId"`
	UserId    string     `json:"userId"`
}

// User defines model for User.
type User struct {
	CreatedAt     time.Time `json:"createdAt"`
	Email         string    `json:"email"`
	EmailVerified *bool     `json:"emailVerified,omitempty"`
	Id            *string   `json:"id,omitempty"`
	Image         *string   `json:"image,omitempty"`
	Name          string    `json:"name"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// Verification defines model for Verification.
type Verification struct {
	CreatedAt  time.Time `json:"createdAt"`
	ExpiresAt  time.Time `json:"expiresAt"`
	Id         *string   `json:"id,omitempty"`
	Identifier string    `json:"identifier"`
	UpdatedAt  time.Time `json:"updatedAt"`
	Value      string    `json:"value"`
}

// ChangeEmailJSONBody defines parameters for ChangeEmail.
type ChangeEmailJSONBody struct {
	// CallbackURL The URL to redirect to after email verification
	CallbackURL *string `json:"callbackURL,omitempty"`

	// NewEmail The new email address to set must be a valid email address
	NewEmail string `json:"newEmail"`
}

// ChangePasswordJSONBody defines parameters for ChangePassword.
type ChangePasswordJSONBody struct {
	// CurrentPassword The current password is required
	CurrentPassword string `json:"currentPassword"`

	// NewPassword The new password to set
	NewPassword string `json:"newPassword"`

	// RevokeOtherSessions Must be a boolean value
	RevokeOtherSessions *bool `json:"revokeOtherSessions,omitempty"`
}

// DeleteUserJSONBody defines parameters for DeleteUser.
type DeleteUserJSONBody struct {
	// CallbackURL The callback URL to redirect to after the user is deleted
	CallbackURL *string `json:"callbackURL,omitempty"`

	// Password The user's password. Required if session is not fresh
	Password *string `json:"password,omitempty"`

	// Token The deletion verification token
	Token *string `json:"token,omitempty"`
}

// GetDeleteUserCallbackParams defines parameters for GetDeleteUserCallback.
type GetDeleteUserCallbackParams struct {
	Token       *string `form:"token,omitempty" json:"token,omitempty"`
	CallbackURL *string `form:"callbackURL,omitempty" json:"callbackURL,omitempty"`
}

// PostGetAccessTokenJSONBody defines parameters for PostGetAccessToken.
type PostGetAccessTokenJSONBody struct {
	// AccountId The account ID associated with the refresh token
	AccountId *string `json:"accountId,omitempty"`

	// ProviderId The provider ID for the OAuth provider
	ProviderId string `json:"providerId"`

	// UserId The user ID associated with the account
	UserId *string `json:"userId,omitempty"`
}

// LinkSocialAccountJSONBody defines parameters for LinkSocialAccount.
type LinkSocialAccountJSONBody struct {
	AdditionalData *string `json:"additionalData,omitempty"`

	// CallbackURL The URL to redirect to after the user has signed in
	CallbackURL *string `json:"callbackURL,omitempty"`

	// DisableRedirect Disable automatic redirection to the provider. Useful for handling the redirection yourself
	DisableRedirect *bool `json:"disableRedirect,omitempty"`

	// ErrorCallbackURL The URL to redirect to if there is an error during the link process
	ErrorCallbackURL *string `json:"errorCallbackURL,omitempty"`
	IdToken          *struct {
		AccessToken  *string        `json:"accessToken,omitempty"`
		Nonce        *string        `json:"nonce,omitempty"`
		RefreshToken *string        `json:"refreshToken,omitempty"`
		Scopes       *[]interface{} `json:"scopes,omitempty"`
		Token        string         `json:"token"`
	} `json:"idToken,omitempty"`
	Provider      string `json:"provider"`
	RequestSignUp *bool  `json:"requestSignUp,omitempty"`

	// Scopes Additional scopes to request from the provider
	Scopes *[]interface{} `json:"scopes,omitempty"`
}

// PostOrganizationAcceptInvitationJSONBody defines parameters for PostOrganizationAcceptInvitation.
type PostOrganizationAcceptInvitationJSONBody struct {
	// InvitationId The ID of the invitation to accept
	InvitationId string `json:"invitationId"`
}

// PostOrganizationAddTeamMemberJSONBody defines parameters for PostOrganizationAddTeamMember.
type PostOrganizationAddTeamMemberJSONBody struct {
	// TeamId The team the user should be a member of.
	TeamId string `json:"teamId"`

	// UserId The user Id which represents the user to be added as a member.
	UserId string `json:"userId"`
}

// PostOrganizationCancelInvitationJSONBody defines parameters for PostOrganizationCancelInvitation.
type PostOrganizationCancelInvitationJSONBody struct {
	// InvitationId The ID of the invitation to cancel
	InvitationId string `json:"invitationId"`
}

// PostOrganizationCheckSlugJSONBody defines parameters for PostOrganizationCheckSlug.
type PostOrganizationCheckSlugJSONBody struct {
	// Slug The organization slug to check. Eg: "my-org"
	Slug string `json:"slug"`
}

// PostOrganizationCreateJSONBody defines parameters for PostOrganizationCreate.
type PostOrganizationCreateJSONBody struct {
	// KeepCurrentActiveOrganization Whether to keep the current active organization active after creating a new one. Eg: true
	KeepCurrentActiveOrganization *bool `json:"keepCurrentActiveOrganization,omitempty"`

	// Logo The logo of the organization
	Logo *string `json:"logo,omitempty"`

	// Metadata The metadata of the organization
	Metadata *string `json:"metadata,omitempty"`

	// Name The name of the organization
	Name string `json:"name"`

	// Slug The slug of the organization
	Slug string `json:"slug"`

	// UserId The user id of the organization creator. If not provided, the current user will be used. Should only be used by admins or when called by the server. server-only. Eg: "user-id"
	UserId *string `json:"userId,omitempty"`
}

// PostOrganizationCreateTeamJSONBody defines parameters for PostOrganizationCreateTeam.
type PostOrganizationCreateTeamJSONBody struct {
	// Name The name of the team. Eg: "my-team"
	Name string `json:"name"`

	// OrganizationId The organization ID which the team will be created in. Defaults to the active organization. Eg: "organization-id"
	OrganizationId *string `json:"organizationId,omitempty"`
}

// PostOrganizationDeleteJSONBody defines parameters for PostOrganizationDelete.
type PostOrganizationDeleteJSONBody struct {
	// OrganizationId The organization id to delete
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationGetInvitationParams defines parameters for GetOrganizationGetInvitation.
type GetOrganizationGetInvitationParams struct {
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostOrganizationHasPermissionJSONBody defines parameters for PostOrganizationHasPermission.
type PostOrganizationHasPermissionJSONBody struct {
	// Permission The permission to check
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Permission *map[string]interface{} `json:"permission,omitempty"`

	// Permissions The permission to check
	Permissions map[string]interface{} `json:"permissions"`
}

// CreateOrganizationInvitationJSONBody defines parameters for CreateOrganizationInvitation.
type CreateOrganizationInvitationJSONBody struct {
	// Email The email address of the user to invite
	Email string `json:"email"`

	// OrganizationId The organization ID to invite the user to
	OrganizationId *string `json:"organizationId,omitempty"`

	// Resend Resend the invitation email, if the user is already invited. Eg: true
	Resend *bool `json:"resend,omitempty"`

	// Role The role(s) to assign to the user. It can be `admin`, `member`, owner. Eg: "member"
	Role   string `json:"role"`
	TeamId string `json:"teamId"`
}

// PostOrganizationLeaveJSONBody defines parameters for PostOrganizationLeave.
type PostOrganizationLeaveJSONBody struct {
	// OrganizationId The organization Id for the member to leave. Eg: "organization-id"
	OrganizationId string `json:"organizationId"`
}

// PostOrganizationRejectInvitationJSONBody defines parameters for PostOrganizationRejectInvitation.
type PostOrganizationRejectInvitationJSONBody struct {
	// InvitationId The ID of the invitation to reject
	InvitationId string `json:"invitationId"`
}

// PostOrganizationRemoveMemberJSONBody defines parameters for PostOrganizationRemoveMember.
type PostOrganizationRemoveMemberJSONBody struct {
	// MemberIdOrEmail The ID or email of the member to remove
	MemberIdOrEmail string `json:"memberIdOrEmail"`

	// OrganizationId The ID of the organization to remove the member from. If not provided, the active organization will be used. Eg: "org-id"
	OrganizationId *string `json:"organizationId,omitempty"`
}

// PostOrganizationRemoveTeamJSONBody defines parameters for PostOrganizationRemoveTeam.
type PostOrganizationRemoveTeamJSONBody struct {
	// OrganizationId The organization ID which the team falls under. If not provided, it will default to the user's active organization. Eg: "organization-id"
	OrganizationId *string `json:"organizationId,omitempty"`

	// TeamId The team ID of the team to remove. Eg: "team-id"
	TeamId string `json:"teamId"`
}

// PostOrganizationRemoveTeamMemberJSONBody defines parameters for PostOrganizationRemoveTeamMember.
type PostOrganizationRemoveTeamMemberJSONBody struct {
	// TeamId The team the user should be removed from.
	TeamId string `json:"teamId"`

	// UserId The user which should be removed from the team.
	UserId string `json:"userId"`
}

// SetActiveOrganizationJSONBody defines parameters for SetActiveOrganization.
type SetActiveOrganizationJSONBody struct {
	OrganizationId *string `json:"organizationId,omitempty"`

	// OrganizationSlug The organization slug to set as active. It can be null to unset the active organization if organizationId is not provided. Eg: "org-slug"
	OrganizationSlug *string `json:"organizationSlug,omitempty"`
}

// PostOrganizationSetActiveTeamJSONBody defines parameters for PostOrganizationSetActiveTeam.
type PostOrganizationSetActiveTeamJSONBody struct {
	TeamId *string `json:"teamId,omitempty"`
}

// PostOrganizationUpdateJSONBody defines parameters for PostOrganizationUpdate.
type PostOrganizationUpdateJSONBody struct {
	Data struct {
		// Logo The logo of the organization
		Logo *string `json:"logo,omitempty"`

		// Metadata The metadata of the organization
		Metadata *string `json:"metadata,omitempty"`

		// Name The name of the organization
		Name *string `json:"name,omitempty"`

		// Slug The slug of the organization
		Slug *string `json:"slug,omitempty"`
	} `json:"data"`

	// OrganizationId The organization ID. Eg: "org-id"
	OrganizationId *string `json:"organizationId,omitempty"`
}

// UpdateOrganizationMemberRoleJSONBody defines parameters for UpdateOrganizationMemberRole.
type UpdateOrganizationMemberRoleJSONBody struct {
	// MemberId The member id to apply the role update to. Eg: "member-id"
	MemberId string `json:"memberId"`

	// OrganizationId An optional organization ID which the member is a part of to apply the role update. If not provided, you must provide session headers to get the active organization. Eg: "organization-id"
	OrganizationId *string `json:"organizationId,omitempty"`

	// Role The new role to be applied. This can be a string or array of strings representing the roles. Eg: ["admin", "sale"]
	Role string `json:"role"`
}

// PostOrganizationUpdateTeamJSONBody defines parameters for PostOrganizationUpdateTeam.
type PostOrganizationUpdateTeamJSONBody struct {
	Data struct {
		CreatedAt      *string `json:"createdAt,omitempty"`
		Id             *string `json:"id,omitempty"`
		Name           *string `json:"name,omitempty"`
		OrganizationId *string `json:"organizationId,omitempty"`
		UpdatedAt      *string `json:"updatedAt,omitempty"`
	} `json:"data"`

	// TeamId The ID of the team to be updated. Eg: "team-id"
	TeamId string `json:"teamId"`
}

// PostRefreshTokenJSONBody defines parameters for PostRefreshToken.
type PostRefreshTokenJSONBody struct {
	// AccountId The account ID associated with the refresh token
	AccountId *string `json:"accountId,omitempty"`

	// ProviderId The provider ID for the OAuth provider
	ProviderId string `json:"providerId"`

	// UserId The user ID associated with the account
	UserId *string `json:"userId,omitempty"`
}

// RequestPasswordResetJSONBody defines parameters for RequestPasswordReset.
type RequestPasswordResetJSONBody struct {
	// Email The email address of the user to send a password reset email to
	Email string `json:"email"`

	// RedirectTo The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
	RedirectTo *string `json:"redirectTo,omitempty"`
}

// ResetPasswordJSONBody defines parameters for ResetPassword.
type ResetPasswordJSONBody struct {
	// NewPassword The new password to set
	NewPassword string `json:"newPassword"`

	// Token The token to reset the password
	Token *string `json:"token,omitempty"`
}

// ResetPasswordCallbackParams defines parameters for ResetPasswordCallback.
type ResetPasswordCallbackParams struct {
	// CallbackURL The URL to redirect the user to reset their password
	CallbackURL string `form:"callbackURL" json:"callbackURL"`
}

// PostRevokeOtherSessionsJSONBody defines parameters for PostRevokeOtherSessions.
type PostRevokeOtherSessionsJSONBody = map[string]interface{}

// PostRevokeSessionJSONBody defines parameters for PostRevokeSession.
type PostRevokeSessionJSONBody struct {
	// Token The token to revoke
	Token string `json:"token"`
}

// PostRevokeSessionsJSONBody defines parameters for PostRevokeSessions.
type PostRevokeSessionsJSONBody = map[string]interface{}

// SendVerificationEmailJSONBody defines parameters for SendVerificationEmail.
type SendVerificationEmailJSONBody struct {
	// CallbackURL The URL to use for email verification callback
	CallbackURL *string `json:"callbackURL"`

	// Email The email to send the verification email to
	Email string `json:"email"`
}

// SignInEmailJSONBody defines parameters for SignInEmail.
type SignInEmailJSONBody struct {
	// CallbackURL Callback URL to use as a redirect for email verification
	CallbackURL *string `json:"callbackURL,omitempty"`

	// Email Email of the user
	Email string `json:"email"`

	// Password Password of the user
	Password   string  `json:"password"`
	RememberMe *string `json:"rememberMe,omitempty"`
}

// SocialSignInJSONBody defines parameters for SocialSignIn.
type SocialSignInJSONBody struct {
	AdditionalData *string `json:"additionalData,omitempty"`

	// CallbackURL Callback URL to redirect to after the user has signed in
	CallbackURL *string `json:"callbackURL,omitempty"`

	// DisableRedirect Disable automatic redirection to the provider. Useful for handling the redirection yourself
	DisableRedirect *bool `json:"disableRedirect,omitempty"`

	// ErrorCallbackURL Callback URL to redirect to if an error happens
	ErrorCallbackURL *string `json:"errorCallbackURL,omitempty"`
	IdToken          *struct {
		// AccessToken Access token from the provider
		AccessToken *string `json:"accessToken,omitempty"`

		// ExpiresAt Expiry date of the token
		ExpiresAt *float32 `json:"expiresAt,omitempty"`

		// Nonce Nonce used to generate the token
		Nonce *string `json:"nonce,omitempty"`

		// RefreshToken Refresh token from the provider
		RefreshToken *string `json:"refreshToken,omitempty"`

		// Token ID token from the provider
		Token string `json:"token"`
	} `json:"idToken,omitempty"`

	// LoginHint The login hint to use for the authorization code request
	LoginHint          *string `json:"loginHint,omitempty"`
	NewUserCallbackURL *string `json:"newUserCallbackURL,omitempty"`
	Provider           string  `json:"provider"`

	// RequestSignUp Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
	RequestSignUp *bool `json:"requestSignUp,omitempty"`

	// Scopes Array of scopes to request from the provider. This will override the default scopes passed.
	Scopes *[]interface{} `json:"scopes,omitempty"`
}

// SignOutJSONBody defines parameters for SignOut.
type SignOutJSONBody = map[string]interface{}

// SignUpWithEmailAndPasswordJSONBody defines parameters for SignUpWithEmailAndPassword.
type SignUpWithEmailAndPasswordJSONBody struct {
	// CallbackURL The URL to use for email verification callback
	CallbackURL *string `json:"callbackURL,omitempty"`

	// Email The email of the user
	Email string `json:"email"`

	// Image The profile image URL of the user
	Image *string `json:"image,omitempty"`

	// Name The name of the user
	Name string `json:"name"`

	// Password The password of the user
	Password string `json:"password"`

	// RememberMe If this is false, the session will not be remembered. Default is `true`.
	RememberMe *bool `json:"rememberMe,omitempty"`
}

// PostUnlinkAccountJSONBody defines parameters for PostUnlinkAccount.
type PostUnlinkAccountJSONBody struct {
	AccountId  *string `json:"accountId,omitempty"`
	ProviderId string  `json:"providerId"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	// Image The image of the user
	Image *string `json:"image"`

	// Name The name of the user
	Name *string `json:"name,omitempty"`
}

// GetVerifyEmailParams defines parameters for GetVerifyEmail.
type GetVerifyEmailParams struct {
	// Token The token to verify the email
	Token string `form:"token" json:"token"`

	// CallbackURL The URL to redirect to after email verification
	CallbackURL *string `form:"callbackURL,omitempty" json:"callbackURL,omitempty"`
}

// ChangeEmailJSONRequestBody defines body for ChangeEmail for application/json ContentType.
type ChangeEmailJSONRequestBody ChangeEmailJSONBody

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody ChangePasswordJSONBody

// DeleteUserJSONRequestBody defines body for DeleteUser for application/json ContentType.
type DeleteUserJSONRequestBody DeleteUserJSONBody

// PostGetAccessTokenJSONRequestBody defines body for PostGetAccessToken for application/json ContentType.
type PostGetAccessTokenJSONRequestBody PostGetAccessTokenJSONBody

// LinkSocialAccountJSONRequestBody defines body for LinkSocialAccount for application/json ContentType.
type LinkSocialAccountJSONRequestBody LinkSocialAccountJSONBody

// PostOrganizationAcceptInvitationJSONRequestBody defines body for PostOrganizationAcceptInvitation for application/json ContentType.
type PostOrganizationAcceptInvitationJSONRequestBody PostOrganizationAcceptInvitationJSONBody

// PostOrganizationAddTeamMemberJSONRequestBody defines body for PostOrganizationAddTeamMember for application/json ContentType.
type PostOrganizationAddTeamMemberJSONRequestBody PostOrganizationAddTeamMemberJSONBody

// PostOrganizationCancelInvitationJSONRequestBody defines body for PostOrganizationCancelInvitation for application/json ContentType.
type PostOrganizationCancelInvitationJSONRequestBody PostOrganizationCancelInvitationJSONBody

// PostOrganizationCheckSlugJSONRequestBody defines body for PostOrganizationCheckSlug for application/json ContentType.
type PostOrganizationCheckSlugJSONRequestBody PostOrganizationCheckSlugJSONBody

// PostOrganizationCreateJSONRequestBody defines body for PostOrganizationCreate for application/json ContentType.
type PostOrganizationCreateJSONRequestBody PostOrganizationCreateJSONBody

// PostOrganizationCreateTeamJSONRequestBody defines body for PostOrganizationCreateTeam for application/json ContentType.
type PostOrganizationCreateTeamJSONRequestBody PostOrganizationCreateTeamJSONBody

// PostOrganizationDeleteJSONRequestBody defines body for PostOrganizationDelete for application/json ContentType.
type PostOrganizationDeleteJSONRequestBody PostOrganizationDeleteJSONBody

// PostOrganizationHasPermissionJSONRequestBody defines body for PostOrganizationHasPermission for application/json ContentType.
type PostOrganizationHasPermissionJSONRequestBody PostOrganizationHasPermissionJSONBody

// CreateOrganizationInvitationJSONRequestBody defines body for CreateOrganizationInvitation for application/json ContentType.
type CreateOrganizationInvitationJSONRequestBody CreateOrganizationInvitationJSONBody

// PostOrganizationLeaveJSONRequestBody defines body for PostOrganizationLeave for application/json ContentType.
type PostOrganizationLeaveJSONRequestBody PostOrganizationLeaveJSONBody

// PostOrganizationRejectInvitationJSONRequestBody defines body for PostOrganizationRejectInvitation for application/json ContentType.
type PostOrganizationRejectInvitationJSONRequestBody PostOrganizationRejectInvitationJSONBody

// PostOrganizationRemoveMemberJSONRequestBody defines body for PostOrganizationRemoveMember for application/json ContentType.
type PostOrganizationRemoveMemberJSONRequestBody PostOrganizationRemoveMemberJSONBody

// PostOrganizationRemoveTeamJSONRequestBody defines body for PostOrganizationRemoveTeam for application/json ContentType.
type PostOrganizationRemoveTeamJSONRequestBody PostOrganizationRemoveTeamJSONBody

// PostOrganizationRemoveTeamMemberJSONRequestBody defines body for PostOrganizationRemoveTeamMember for application/json ContentType.
type PostOrganizationRemoveTeamMemberJSONRequestBody PostOrganizationRemoveTeamMemberJSONBody

// SetActiveOrganizationJSONRequestBody defines body for SetActiveOrganization for application/json ContentType.
type SetActiveOrganizationJSONRequestBody SetActiveOrganizationJSONBody

// PostOrganizationSetActiveTeamJSONRequestBody defines body for PostOrganizationSetActiveTeam for application/json ContentType.
type PostOrganizationSetActiveTeamJSONRequestBody PostOrganizationSetActiveTeamJSONBody

// PostOrganizationUpdateJSONRequestBody defines body for PostOrganizationUpdate for application/json ContentType.
type PostOrganizationUpdateJSONRequestBody PostOrganizationUpdateJSONBody

// UpdateOrganizationMemberRoleJSONRequestBody defines body for UpdateOrganizationMemberRole for application/json ContentType.
type UpdateOrganizationMemberRoleJSONRequestBody UpdateOrganizationMemberRoleJSONBody

// PostOrganizationUpdateTeamJSONRequestBody defines body for PostOrganizationUpdateTeam for application/json ContentType.
type PostOrganizationUpdateTeamJSONRequestBody PostOrganizationUpdateTeamJSONBody

// PostRefreshTokenJSONRequestBody defines body for PostRefreshToken for application/json ContentType.
type PostRefreshTokenJSONRequestBody PostRefreshTokenJSONBody

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody RequestPasswordResetJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody ResetPasswordJSONBody

// PostRevokeOtherSessionsJSONRequestBody defines body for PostRevokeOtherSessions for application/json ContentType.
type PostRevokeOtherSessionsJSONRequestBody = PostRevokeOtherSessionsJSONBody

// PostRevokeSessionJSONRequestBody defines body for PostRevokeSession for application/json ContentType.
type PostRevokeSessionJSONRequestBody PostRevokeSessionJSONBody

// PostRevokeSessionsJSONRequestBody defines body for PostRevokeSessions for application/json ContentType.
type PostRevokeSessionsJSONRequestBody = PostRevokeSessionsJSONBody

// SendVerificationEmailJSONRequestBody defines body for SendVerificationEmail for application/json ContentType.
type SendVerificationEmailJSONRequestBody SendVerificationEmailJSONBody

// SignInEmailJSONRequestBody defines body for SignInEmail for application/json ContentType.
type SignInEmailJSONRequestBody SignInEmailJSONBody

// SocialSignInJSONRequestBody defines body for SocialSignIn for application/json ContentType.
type SocialSignInJSONRequestBody SocialSignInJSONBody

// SignOutJSONRequestBody defines body for SignOut for application/json ContentType.
type SignOutJSONRequestBody = SignOutJSONBody

// SignUpWithEmailAndPasswordJSONRequestBody defines body for SignUpWithEmailAndPassword for application/json ContentType.
type SignUpWithEmailAndPasswordJSONRequestBody SignUpWithEmailAndPasswordJSONBody

// PostUnlinkAccountJSONRequestBody defines body for PostUnlinkAccount for application/json ContentType.
type PostUnlinkAccountJSONRequestBody PostUnlinkAccountJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9e28cN7LvVyHmXiD3AhrJm937xxWwOEexvFkhTmzo4cVBYhxT0zUzXPWQHZIteTbw",
	"dz/gq5vdzX7MaCR5k/rL1jSbXXz+flUsVv02W4hNIThwrWanv83UYg0bav97tliIkmvz30KKAqRmYB/Q",
	"xQKUuhZ3wM2felvA7HSmtGR8NftyFD9/87lgEtSZrWUp5Ibq2eksoxrmmm1gdpR823z2IkvWvZBANWSu",
	"wgyWtMxNjd8DB2keEKqJLLmvfNoXWfpTLOtvYkGVehAy/WIhxT3LQPY0QcJSglr3Vx4X2KMD1UKYXxIV",
	"l0VWd960ykrV0w4r568lk5DNTn+ORq3R/qqCeORiQT5W3xS3/4SFNt+84PdMU80E7869pxh/2FCWJzsM",
	"du/9vslk2tQ7JYRcUc7+ZdvcN2tEnh5UpakuVbM7CuCZeZyQTwPdTBnQlkihl6rvxZ3THNy6qanB/RE2",
	"tyBHBvZRXb1DZ9Y9tnFiPWIFdDqsmvn2a3EfpfrlXfT6U/ZOLlYi+WADmmZU0+RDTjc9sy8vV+N9Y1/3",
	"hcc64gqUSvYBXWh2D+/GR9cVvO6b6E8DIgfcKoqzLJOgVPKp7oWNPXf3sxU4kN975scbgROvb7ev6kwN",
	"vBmwp5z5vXN4woaxc9+mF0BnjxheCqZHnn6/1P0LZeoM8FUMDu+NGm3G0+O5efIBJFsyyBpfXNJcgWkU",
	"zd7xfDs71bKEqu5bIXKgfGjRbugKdpt2jTl1kKanJ10A7ukEzPXQ4jkp2OF2zwy4NuMrn6nTj2b3NC9h",
	"fJFEkoV3+knU0AAZ2IVFKZneXhl1zcNjwX6A7Wsh7pjnNmohWeHGcHb2/oL8AFtCS702YrjBJfeMkoV7",
	"xRC32ems+svN22a1lSjuV9P4W6AS5Fmp192PfmefEYsJrS8bNmBlN6vLFqsrX2tdzL58sax5KdJtuYQl",
	"SOALIEshyVaUkvyN3YIk3wu9JhdcacoXVmCmDdebRU/P3l+YEQDpeMbsT8evjl9ZICiA04LNTmd/Pn51",
	"/BejylC9tr174hWceRBpBbor2fegiV4D8YWJKUy8OpSR2619GNSjmf2grGDHvO117gvzETN7VCG4cuP7",
	"7atXdvUJrj1g06LIfXee/FO5per0d/s0y5h5RPP30fL1+1xzRQfal36lsRPWm0SZ3M932Hufbm/tLLxZ",
	"+/PJRRW/Y1t35HomUfjLUWvkr0pr9DBC/WXHgWp24AaUSje3JWEoOEW672hGLuHXEpQ+JjeqpHm+JVkJ",
	"RAuyYUoxviIFlXQDGqQ6IkISxu9pzrLo52PXuD99bY274WZrEZL9C7Jjct5sVdSS5gbkW/Pnp2rNqNh/",
	"E/KWZRnwY/JfoiSZIFxosqb3QAqQVn7BTVOcOY3oNVNEghKlXIBplxamoIEo98yoPVW7/vJi7fpJaPI3",
	"UfLsmFyvgUg37SCrZX+gyrZ1aUtZeb/9/y8m77UQ5EfKt2GBKDcediDg8wLAbN1m3zb8gORsw/QxuZZb",
	"QleUcZJTDdI24v893bofbcQF1yA5zckVyHuQ5I2UQpoBYIqYqWFA5zaHDXlgem1bo1xBvabawCdZUG7H",
	"hH0+bjCM2enPvzVA/uePX8yqpCtlFuq5p1AfzTsnizXlK5hXIFAIZTuiiXOvbak3npb6CfKdyLaP6L4F",
	"zfNburi7uXzbhWUzD28u35oVIyFjEhbaLqylBkmssOQ+prwJjsfh4U1oVbdyDg++HupUd1O9Ak02pdLk",
	"Fgglbg9qFBon8OGj6W2wLmog+ssj+ULvdGwBnTX/Ef+ciKWdTa5dbvjNXFu45vEyz+mt4V8NEpE2Xjbn",
	"c2YkBUWY+4CfJXbvUA5rl2U+S2logZj8bwnL2ensf53UJxwn/njjxCqj7e72wkzBnDdxe4Nsvt2QRRLm",
	"W6QESAmQEuxBCb59MXlvuF/KZu8ib7hmentM3JqnuQSabQl8ZkorJC+/O/ISH+0G/tKU1/EXp8v7wgEH",
	"vdqY4jvvQ70HozyllMD1+0jeLjPxhWpB7Y7hd9U0zxmu0FCdqjLHclL1SLgXd/BOr0H6A50Eyv9YsSMP",
	"3ySYxdqo3iVGUXe2O+L52VJ1KNPa9+CBKAi79h1ww2aE6ZPwsyIPIM2OaHorm8KYyilm9FiIf6yBV3PT",
	"brS+8O729O5saJLe5iKoKg8G6Cnm+Jbktq9qgrmmitwCcE/X4yncMSN1hS05+7UEUtthWwL3G566dRVS",
	"LFkOxBaxykVP40vJpgxrsGQlFhzdwJigLav28PDnVGni39jvYIHF/gDxKcOHelh2MGZ37G5TKF5Y7Q2u",
	"7Rl5hpwbOTdybjTD/UGZbAY5aJhXVCHJYs9toX7W6p7fuEfPZKQLBfqtdRWSMUVcM5M0thjksKaCb1RF",
	"Y4/tnDN7nuFngbAxvzokqHXSkS7N+Uz9VjB7vBpZFUlwjZkwr17UlldJX9vxunY7f9w1brirJtW46a5t",
	"jvPfONoNhszkaDcBTXJID5AeID1AetCiBycBcXtdWl4HSNaCLMSmsKShbGyyVtok1HX8W2pSEeq1TjZh",
	"87LNsG5Iv5Ygt7UXUqiwHpcu6joLixZOlG0Ty/wET8Fv+osxVxn+bi9XCR9PfPTj8wD8a8GXzKj3pgtC",
	"qUfBeT3oz4fmDQ0/kD6EcIRwhHCE8D8mhIP5bC9mnzNV5HSrCOXEliSF2/g7eGzFH/c01fBZn6z1Jm92",
	"bBcL/37941viX6x8Q2IJ2l2OjpS4v+P+jvs77u+N/X0Feu6m67yyM6bNuN+DrrwLwwQ3bxyRTJh1S4m/",
	"Tm4YPLeD0AGC90Jpd/mgutd/KJNv4zZ/Fy/CRYmLc0KVEgtm7+BUfRtE7zGdtq/aJ49p7XPzgaVw5uN3",
	"pvvjWxgD197StuM+cX1rRs9PI6mf31fhaaM3DAVNeOrAB3aWXG+Lfdf+GfnQWUYRD2lvFG7NNaaoQZNq",
	"yi2M8r0q3TpDyEfIR8hHyB+GfFXHPhi8Xxi8+kL5hGZ3VT16FHa0HZeaHR/JO+RtH2R5lHN+1Z7JLkKo",
	"SiKuIK4grvyxcSVn/G5udZW8X4t8y/gdocQVq7QyLfrdg8wbV7b4WaX1HEhlrG6hn/eFI9r/tl/lP7Sm",
	"iii24pARllQtM2avf1z6KpJWVns/hJZabKhmi+pzfpOIL/ubLR6WZW610DXlWW52Qqfj1i9tRSkV5Muk",
	"W7O1o77eo+Xu6E6CnXXBIpyVMkhgZsiQs0+k0+2mSnLBF7CfKmiD2MURkKiUdDsUAKkdksYWS0U3qTT/",
	"tGB2Cl+xFb8p0lEKatFa6mM1b4kr4sbB3Q1cSrFpR39otqzHRvACFgLZO+U7x8F2Kam1KPOM3NZzGbIw",
	"/wMNcEfQ7jA90aXVNdDEdU7Zc/egU3Vz3gfptBi1x1QNRlaJrBJZJbJKZJXjrFLZEwrD/FSvveItU5rQ",
	"vGKUynKNGh16mKXSNwrkWaj9keDGNGzUyMnEcIjIRwUkG4kGXLOJSs6uYbtFgZ4wji/rBPDti+QYR/yt",
	"Qp361qRoV4vtIK4iriKuIq4irnZxVUU35sdwVbN7qG+ThzPuQWCtLuQfClgn2v4RARABEAEQARABhhBA",
	"DNzFWcPiLpjezt5fGLEehLxzqR46R8Dv7mYHtQs6yUYsgh2xRu6FiLtJG1SrWoQIhAiECISIPyhERGkk",
	"Tsy8LfScNZMmJU95z2xRQjmpS9upz0lcZdI/OM674uqJ0jQd6ui3FqvP/fbiPFwraTXBijQeuSj+wPOf",
	"rDUHqWMi21S5PrpBkvBcCqERoRGhEaGxBY2NxGkpfMyyuQa6mde7axodfXTLfBsCJJIqKdwIHGZZlKnp",
	"UFhYp2VKhDoAukn5X1AvMhHL4/0utmTkYc0WayKhkKCAaxV7UthvZGY6UlV97HgUdcfTQx0eeHs6rRrS",
	"yfEzr9kGlKabgjyEUIpRTXsF1EwFqLzpC07ZFHsge1dPi2vGVM2aWH6zPPm+l6CmiJg6YKzOC6uZMZQI",
	"LbFjRg0IixUDPCEJQhKEJAhJUIIELShfQN5jJBhmN6/tq1+Vsu9a8/TKPkIIQghCCEIIQoiBkDUs7uYh",
	"3/dE7DDvXLms34cBjfD9LljEwhJTzCKFEeCYvFmdkl9mm+1cyNUvs1HgsB9BwEDAQMBAwEDA2BcwrGFm",
	"II2Sfb7z4aN77WCAcgdQvHbhFM6sM2WjWf05aQQxbzaiMXhnzAYQ+d/c5VPbIy4oE4cHIjg4aDJQkrwX",
	"l4uVSKOdeRKUo1b3dSx5G9A0pHju1hSeTq1tWqaasVr6cdxC98RaRm2ULEtV5QbCrJKLpd2OQoruo8Z4",
	"uow5LM/Jra0uOyZXztQueL4NP5LbLaHZhnFldmZrI17QPK/zfbvlduz/nZt3AyMxX5izbAIl8Vl29mYm",
	"u5rPh1x6GysET6KRECEhQkKEhGgiIbKH0eOsyDIEe7BmxGR8T550bT52KK40DfqN0JHKbf5MAdzRLG5O",
	"H4o3YPvi3J9OV4eOAZ3DISDjx8T7yqkqBEGXlgXx4t92wOHndxzb43z6yQ+mQ59rN8UmEsWfWjNln4lR",
	"nws0pkfV9FvIBV+pZOiHwWSJQ315oLSJnsi1mrhDvsT0YTiegiMBQwKGBAwJ2AABc7ljRlMi7sq03GsH",
	"Y1k70yJm42lkQYrhzaxV+8u44nXENwNvVmJvSke0MiDIIcghyCHIjYGcSx1hVN7I430wmrR3pM1AU5ZX",
	"WfwTanPyknH03OaQMG9FrvCHuzuVjp/URctuTEeRp6NQ7hQUqfJZ7qhutn4MHYiQhZCFkIWQdQDImoct",
	"2+PWLqhzaV5FvyzcbXG3xd0Wd9v0brss83wuWp5Og0qCeWMnZWCGHii49ePWj1s/bv1f1dbfvAPYu+c3",
	"gwTdbsnF+QTzT+OaYL1ZWbGZqfrXEuQ2HIOfOsvK0ElB3xVAI3f3kODjQS1OsKEsTxqOIE5OOTUQuG0A",
	"yDe9tfoCF3sbuuIiP3nvi8FCV94Ld7rJrJOpY8hk5jrQ15YwnNUNriqO+zbRoIT4rY5FOxzSA6QHSA+Q",
	"HuxOD9ZUzevpPOCjGsehrbKpRW+OeUz8nar3cenDOE40Rc+gkLCw3no+d2kiPXhj7drLorNUxrCqmOpJ",
	"Mz6lnnaCr6jS1M55WAdSm/QtjegeDBPJt9rXYn1JhFiEWIRYhFiE2N0h1ukqo7EI67uxu0Xqde/FQjxB",
	"4J5KL+4CoX1EaJZJs0TFshE80LX9UDdBqgqHUz1aFAWeqPTS/t62LdgWHDXIjZkwuQSabf0Xs5Fru0F7",
	"7jbCPPk/6v/aoVSKrXicCe2YXGgz78gtkE/2SumnI/LJTZVPR0Q8cFPGX6yxv6bv1dQhAYdBpaWe+9de",
	"+HJL19byJFaYi8N7Ez2vaWS3gIlIx5COIR1DOoZ0rEnHcqD3MD2e1Vtb/MUuelxkVYI377OrBbFN2P9C",
	"6wHugyCiIKIgoiCiIKIYRGEOSIbzdsavqLFzdfPWs+TqbLpVYcJOxADEAMQAxIB9MCDys1JTbzKYjf4i",
	"eg15Nu6xuMfiHot7bM8e66wgO+2vP/pXcG/FvRX3VtxbcW/t2VujnIlq2KBR26OrI/8VuwfuIkFOsW7U",
	"6RPV7KDBhs6kpFsrVJQxzo2ICoE1o0iElZUEswf+brIHjpuxzOwzu7SWDO4xhiJyA+QGyA2QG4xwAzV+",
	"ymGLkQmxq3sowZOSgQQLaMlYsYGvPxYzxmB+zhjMSCmQUiClQEqBlOJwlMKlQkqemfWwi6gwofU1RAkL",
	"YPcWH0ZJxo3RJPsP3PZ2svha/NuH4im47FZrUedxaFyEmMYJ9gtBsLsL/bClomVLoEqJBbNtqqZyo2G8",
	"zHN6a2RwF0MP4K+fiFTwKBd+dL5BNoFsAtkEson92cROVgorVif7o2sJlZqI5fFURvE1mS6G3D1tbjBU",
	"ZhF+EH4QfhB+DgM/EozIrSh76Uv+l7bo7pf827fSXD1PcNG/Fmtc82o2wfXCuDU2/sDzXzxvDlJHA6uD",
	"NPQojFFkH7yBjXiJeIl4iXi5M15uxP14QJxLW4zQ4Hi0lGKzB1CaSqLkRIcASSfQRfaujuyaxknpo+N4",
	"wKxvcLsu2DcuTt9BbKg3/pjptWNysbSrq5DinmWQHfWle6qyK5cqhLyxN8ynXSxv98vzw3s0p/7NM0ml",
	"ehbjviDrQNaBrANZx/6swzo/jXMOa3R9BOO4dj5WLxU15pw8rNliXR+QLmmeK1LyzMaca7MBph3wZ7Ck",
	"Za7jCHXfqBRP2CH4zB4e54HHhK/YewmTGMiLBbSLFk0rrKPgSyY3blx8KcJ4Zivmq8iy7hpN8wk0azok",
	"mXnoexOt+MgPkB8gP0B+MMYP9jRNBMfqqfzgwFaJUZitXMDUWpR5ZtT8gAzWSrDXpS7HM9I1VpB+PBW4",
	"qw8igjcQ3M8zBHIEcgRyBHIE8gEgV1Vq6X4Av/IpThOqbQfAr0Ky6U6q06fR7SelbxsxAKi8XJnVqkAT",
	"GjT4ONg8L/PcFCi56u8KwpakKZ8Z2dh0EB8RmG/2qOhPDuWYORZxFHEUcRRx9ClwdMRo3gLTSVpwBaoH",
	"NZQPpUF5UQxyfteIPYg9iD2IPYg9Y9jjQjH0Q86Nfb7z2ax77WBwk1Gd+DUXK5FW0cyTlOdWyvC6AU1D",
	"/d2awtOptaWDgpiaeBQYZKwW1at8Wn1zUi1fEvde9zjf3tk3zfblR1RFkQ4gHUA6gHTg35AO+GPZeXDJ",
	"HaQG2qfeNKhUndNOiEvmXo8Fcse0ly4KxGEdyPvA3Qmb2XVbFPm2bk3pWyeaWUF7fa/GoPWME2H/T/MB",
	"F7I69Gd1NbpXtoR7mZkZm1JVPxEFbl9aA81AKlPXqt8MvZOzWX8iVg4PTk4tyC1Y4Rlkfnp7szglriaz",
	"M9JwAdv9ZLbNwiaWtae+odXKSffzLzObvvWX2RH5ZaZoDr/MPo6SEh9apJoO6DCPDvNIupB0IelC0vW1",
	"kK5h239tiIHPTDlkBLqZwrTSxpmDngekDTTDwdl6kI/3RTabAImN0KcT7CE7BD5zXMZ/YG9/+aPnM498",
	"/YF1fWfuGGD3xr/FMdDuowLt9jhAhkFBz0dkbMjYkLEhY3OMTcJSglrPtbiDwbhDtpi3sLgpbt4gpV24",
	"lMhQwNaTomq+imtf4DAEjS4WouS6j+z4x4b0pCK8toXuQKG3N/Va2sJz84GQZv+d6fnqyb6JblLi+taM",
	"4mgk9fMzMjc7rsN06jQ+ev4mDlY8lYj11yzjCTZWYI9v21lybX/da9mfxevGy9LPSNpbhoPFxow1uFLN",
	"wIXgS7YqZZWJG8EfwR/BH8E/gP+5u5tf4b7twnlBlXoQMptLUC7kbZ+PJs/s4Y0rTmxxH50ouu3fQX4/",
	"VO/9e5f2K4dCf+iPnuQko1kmzYqM49fbWw1DjUmeCkHGJCz0dY9nzs3lWxd2wBVrfM3VrtfAZPVJe8hl",
	"1We7kTPFv9HEbX5CEhfx3cZV+MaFUwoVBzpAya8lyG2t8JFP/wFmJv314qcPZ28vzv/7+t0Pb3761PmO",
	"+8iONduX/xrVO0pB4MXiN/WtzUSmgFshcqAcgzGizQBpA9IGpA1TaIOCmjQM2QvCtcAKZI1+TPtIgoKK",
	"IhyMHXB4eB8JmnboqMRzlx179b6esAgWVWOMryochchYvOcHSgRDBEMEQwRDBMNDgeHJbxYNvvRmj7n0",
	"mpZqaIc2fwzN81u6uLNqZCVz2pTewMrX/sXZ0azeuWwbdsUqZooVVK/DEezpTEeW+hqGjqIx7QzdIVTj",
	"IIxVQ2tpQh/dXL7dSaaPB4VN3WNcRtBE0ETQRNBE0BwHzXtxB3Oh1yDn3o9fDSmSprhNumZfCa7/qjpv",
	"tVhiRqFoJmMTHHrOoU2N70xlV+Hz+6ucnW5/KjWtPZg2fBwowpapznkAadaVaWnrhPEopfDF+6r/JHq+",
	"I6IhoiGiIaJNRDS/945DGTFrNK8usQ2A1FVV4kDhbSZZMs2Xxx2/bVWpneoFANANrds7Hmw+dwQ+BD4E",
	"PgQ+BL5nA75pSlxSfRuHwN+DiobKGWIUYhRiFGLUM2KUAp7N70GypW/2vHIaHXR0jV+Z4OZq3voQveLy",
	"Vx5Kb4vPvobcT0sFFledvI0mLOqTQvhMN0VuRm+tdaFOT078L8cLsTmJCvaksK49Y0b9b4Ovrem3ZI82",
	"xDE9+5+RLI/wMn0hJdQ1y+wmCrhuY3vV0kZ3vrjjTfMLdp2GNCWN4fnQHUDntwzczJJsauT2XiKAaI5o",
	"jmiOaD6A5mzF54yfjGE4W3HCuBPG3wThWexh0kJvtuIXz4nZr2OHHw/cVNlrtN5LJg3js+kg/CZOHO45",
	"S/d+a69/bPAwGqtBgouU9eOETRd8BxfP6fbaZndu2wtVujgW/lapmckh6NzsqDWeYWRcnW5Sni5prhJI",
	"3uszHD7fe+G4lHYoR5mXHY6RYLE3pkwnYlxoxlHl32Xr2sGiQObkEnQpuSLA4mNnkoGmLFcGPKqJbOY/",
	"miCQtCBpQdLyxyYtNqDDVNZCiSseB5JokRb73FGXw8XTyDLmorme+9BnHejZidjUXr+C0KWGyGVrbbRk",
	"tuKQEZbEwowpg4GXDeCNP3buCpg9TGyoZovqc36T0FGIDrPFw7LMLbNaU57lVRTW6KWtKKWCfDlLgbq9",
	"YPt63+azpY1yZ9XrNS0KsIcaQxEuBgNrDMSWqFKnDgUhgTgARos6mkdbYgPziWXDF91Xw0sbHfXL0YwL",
	"vkhYEX4yP5txzlxsXg4yBFXu5T7t+B09EWimN7GHhF2cT69kotfD0SwXK8b/zrjuzdzAOFkzrmM7nQ3q",
	"4mHam+lEVqFDMnYcPBha15qEvXFresKg2OrNznFTJEc/Zwum820QxC7TeVlUS8iSZr88LzauuKvO7KuG",
	"svrm1YRaJleUWogCEoa1syp0si3glpKTpTNofkN/YHlOxD1IyTI30TxLD3UYrQOyKJOwjc/cGzznj6Cc",
	"9KkfqG6guoHqBqobqG78u6obotQjioYom9cl0seabMXflfordr7x52F4jx0RAxEDEQMRY1/EKItJp2pl",
	"4YO4+MivE0/Xbop/ML22Z1JnPDt4qJfDOsjs7ucyckjGNklXCx9BdslyILaIFXOkrmmZGHc/8LuOY/Xs",
	"dOjXmtNLt68xRZwC2rydYbR0M2Nt5DlXi93/va7OFPlkFOtPx+O+sD5S/KRTxS9PEwWgZbVoQFUwMnk7",
	"T33bZ/Lh3uRUB/8IwfjtwtwnwcE+kRTjysMgpCt2nkOQJSW3Kn3tPLWmitwCcL86Y7eiyITB+sIn9yZl",
	"OPzSrBpfSjZlWB+3cgeyMnSH/0C5GMKoxivtQz0sk1MyNKve1QBk3efCjHb9g3wd+Try9d35+rcvJu8N",
	"L6QwPWxP7N5wzfTWnidIQnMJNNu6BFDWmrukLHcnR27V20WPKsfvSOUoec743TxkNOhPD2bLEcqj5Afd",
	"q2Ku1FlV4glyS4ykhviKEzJgpEdEXERctJAhXD0Crlwqy0oxH0scPnio4srduEeHgaoBLdZpr03l8klV",
	"1S9Pbn7ZyRsBEQ4RDhEOEQ4RbhDhrLV1W1+OTkYwtra/bWSsbQJBE+a+B+3Kv6kM9FMjFN+3vtMTEvip",
	"AhQHV+Xk/avx2MTPFYt4j1vJwaY+FnXkER5/fi5goBIEYARgBGAE4CkA3H6JFuwH2L4W4o6Bee0oUY2T",
	"wmGp9du24TxOT05ysaD5Wih9+udXr16d0IKdmPU7i77duUnjj9+BZ4Vg3KYooJpQCYTxRV5mITvcd6AN",
	"MtoUt7fb4GJvp6uC6HXzpumTgkptWIKZJEVerhg/rmEzdMCXj1/+JwAA//9SO70tVMQBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
