name: Release
on:
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      checks: write
    uses: ./.github/workflows/main.yml

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()